sudo: disabled
dist: trusty

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-dev

compiler:
    - clang
    - gcc

before_script:
    - mkdir build
    - cd build
    - cmake ..
    
script:
    - make
    - ./tests
